services:
    keywords_publisher:
        container_name: keyword_publisher
        restart: always
        build:
            context: ..
            dockerfile: ./docker/keywordsPublisher/Dockerfile 
        env_file: 
          - path: ../.beta.env 
        depends_on:
          - mongodb
          - redis
          - openobserve

    keywords_retry:
        container_name: keyword_retry
        restart: always
        build:
            context: ..
            dockerfile: ./docker/keywordsRetry/Dockerfile 
        env_file: 
          - path: ../.beta.env 
        depends_on:
          - mongodb
          - redis
          - openobserve

    crawler:
        container_name: crawler
        restart: always
        build:
            context: ..
            dockerfile: ./docker/crawler/Dockerfile
        env_file:
          - path: ../.beta.env
        cap_add:
            - SYS_ADMIN
        shm_size: 1gb
        # deploy:
        #     resources:
        #         limits:
        #             cpus: "4"
        #             memory: 4G
        depends_on:
          - mongodb
          - redis
          - openobserve


    mongodb:
        container_name: mongodb
        build:
            context: ..
            dockerfile: ./docker/mongo/Dockerfile
        ports:
            - "27017:27017"
        env_file:
          - path: .env
        volumes:
            - mongodb_data:/data/db

    redis:
        container_name: redis 
        image: redis:latest
        env_file:
          - path: .env
        command: redis-server --requirepass "$REDIS_PASSWORD"
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
    
    openobserve:
      container_name: open_observe
      image: public.ecr.aws/zinclabs/openobserve:latest
      restart: unless-stopped
      env_file:
          - path: .env
      ports:
        - "5080:5080"
      volumes:
        - zo_data:/data

volumes:
    redis_data:
    mongodb_data:
    zo_data:
