# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY status_checker /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir telethon flask "flask[async]"


# Expose the Flask port
EXPOSE 5000

# Command to run the Flask application
CMD ["python", "telegram_channel.py"]
