const cheerio = require("cheerio");
const chromium = require("chrome-aws-lambda");
const http = require("https");
const request = require("request");
const url = require("url");
let contents = "";
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function extractWithChromium(url){
  let browser = null;
  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    const page = await browser.newPage();
    const navigationPromise = page.waitForNavigation({ waitUntil: 'domcontentloaded', timeout: 5000 });
    await page.goto(url);
    await navigationPromise;
    const source = await page.content();

    // Upload the HTML content to S3
    // const params = {
    //   Bucket: 'ops-tools-bytescare',
    //   Key: 'test/test.html',
    //   Body: source,
    //   ContentType: 'text/html',
    // };

    // await s3.putObject(params).promise();
    
    await browser.close();
    return source;
  } catch (error) {
    console.error('Error:', error);
    await browser.close();
    return "";
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

async function extract(source, callback, retryCount = 0) {
  try {
    const options = {
      url: source,
      method: "GET",
      headers: {
        Accept: "application/json",
        "Accept-Charset": "utf-8",
        "User-Agent": "Mozilla/5.0",
      },
      timeout: 6000,
    };
    
    if(retryCount > 0){
      options.proxy = "http://package-10001:uHUtgPyRMmABDjT0@rotating.proxyempire.io:5000";
    }
    
    var result = await new Promise((resolve, reject) => {
      request(options, function (err, res, body) {
        if (err) {
          return reject(err);
        }
        contents = body;
        return resolve(body);
      });
    });

    if (contents.length < 10 || contents.includes('This error was generated by Mod_Security')) {
      if (retryCount < 3) {
        console.log("Retrying with proxy...");
        await new Promise((resolve) => setTimeout(resolve, 5000)); // 5-second delay
        return await extract(source, callback, retryCount + 1);
      } else {
        result = await extractWithChromium(source);
      }
    }

    var $ = cheerio.load(result);
    let columns = [];
    let text = $("body")
      .contents()
      .toArray()
      .map((element) => cheerio(element).text().trim())
      .join(" ")
      .split(/\t|\s/gi)
      .filter((el) => el != "")
      .join(" ");

    let obj = {};
    obj.text = text;

    //   console.log(domain);
    // }
    // columns.push(obj);

    const jsonScripts = $('script[type="application/ld+json"]');

    var published_date;
    var updated_date;

    try {
      jsonScripts.each(function () {
        const json_content_str = $(this).html();
        const json_content = json_content_str && JSON.parse(json_content_str);
        console.log(json_content);

        if (json_content.datePublished) {
          published_date = json_content.datePublished;
        }
      });

      if (!published_date) {
        published_date = $('meta[itemprop="datePublished"]').attr("content");
      }

      if (!published_date) {
        published_date = $('meta[property="article:published_time"]').attr(
          "content"
        );
      }
      if (!published_date) {
        published_date = $("li.ipc-inline-list__item").first().text().trim();
      }
      if (!published_date) {
        published_date = $("time").attr("datetime");
      }

      if (!published_date) {
        const parsedUrl = url.parse(source);
        const domain = parsedUrl.hostname;
        console.log(domain);
        switch (domain) {
          case "":
            published_date = "";
            updated_date = "";
            break;
          case "www.business-standard.com":
            //published_date = $('meta[itemprop="datePublished"]').attr("content");
            //updated_date = $('span[itemprop="datePublished"]').attr("content") + "T" + $('span[itemprop="datePublished"]').text().split(" ")[8] + ":00+05:30";
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "timesofindia.indiatimes.com":
            //Generic
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            if (!published_date) {
              published_date = $(
                'meta[property="article:published_time"]'
              ).attr("content");
              updated_date = $('meta[property="article:modified_time"]').attr(
                "content"
              );
            }
            //India, WORLD NEWS, BUSINESS NEWS, GADGET, AUTO
            if (!published_date) {
              published_date = $("div.yYIu-.byline > span").text().trim();
              updated_date = published_date;
            }
            //international, lifestyle, home, astrology
            if (!published_date) {
              published_date = $("div._3Mkg-.byline")
                .text()
                .trim()
                .split("|")
                .pop()
                .trim();
              updated_date = published_date;
            } else {
              break;
            }
            //sports
            if (!published_date) {
              published_date = $("div._3mMxl > meta").attr("content");
              updated_date = published_date;
            } else {
              break;
            }
            //home
            if (!published_date) {
              published_date = $("span.time_cptn > span > time").attr(
                "datetime"
              );
              updated_date = published_date;
            } else {
              break;
            }
            //blog
            if (!published_date) {
              published_date = $("div.show-header > div.meta > span")
                .first()
                .text();
              updated_date = published_date;
            } else {
              break;
            }
            //entertainment
            if (!published_date) {
              published_date = (
                $('div.as_byline > div[data-plugin="dateformat"]').attr(
                  "dateval"
                ) || ""
              )
                .split("Created: ")
                .pop()
                .trim();
              updated_date = published_date;
            } else {
              break;
            }

            //lifestyle
            if (!published_date) {
              published_date = (
                $("div.photostory_heading > h4")
                  .first()
                  .contents()
                  .filter(function () {
                    return this.type === "text";
                  })
                  .text() || ""
              )
                .split("Last updated on -")
                .pop()
                .trim();
              updated_date = published_date;
            } else {
              break;
            }
            break;

          case "blogs.timesofindia.indiatimes.com":
            //AS this URL redirecting to timesofindia.indiatimes.com, output not coming
            published_date = $("div.show-header > div.meta > span")
              .first()
              .text();
            updated_date = published_date;
            break;
          case "cricket.timesofindia.indiatimes.com":
            //AS this URL redirecting to timesofindia.indiatimes.com, output not coming
            published_date = $("div.yYIu-.byline > span").text().trim();
            updated_date = published_date;
            break;

          case "economictimes.com":
          case "m.economictimes.com":
          case "economictimes.indiatimes.com":
            //Generic
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            if (!published_date) {
              published_date = $(
                'meta[property="article:published_time"]'
              ).attr("content");
              updated_date = $('meta[property="article:modified_time"]').attr(
                "content"
              );
            }
            //ET Prime
            if (!published_date) {
              published_date = $("div.p_byline > time").text().trim();
              updated_date = published_date;
            }
            //ET Normal
            if (!published_date) {
              published_date = new Date(
                parseInt($("div.artByline > time").attr("data-dt"))
              );
              updated_date = published_date;
            }
            break;
          case "indianexpress.com":
          case "www.indianexpress.com":
            //published_date = $('span[itemprop="dateModified"]').attr("content");
            //updated_date = published_date;
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            break;
          case "www.dnaindia.com":
          case "dnaindia.com":
            published_date = $("div.article-author-txt > p")
              .contents()
              .filter(function () {
                return this.type === "text";
              })
              .last()
              .text()
              .split("Updated: ")
              .pop();
            updated_date = published_date;
            break;
          case "zeenews.india.com":
            published_date = $("div.articleauthor_details > span")
              .contents()
              .filter(function () {
                return this.type === "text";
              })
              .last()
              .text();
            updated_date = published_date;
            break;
          case "www.india.com":
          case "india.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            // published_date = $('section.authors-m.eventtracker > aside.by-aut').text().split("ed:").pop().trim();
            // updated_date = published_date;
            break;
          case "www.jansatta.com":
          case "jansatta.com":
          case "www.financialexpress.com":
          case "financialexpress.com":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            // published_date = $('div.ie-network-post-meta-date > time').attr("datetime");
            // updated_date = published_date;
            break;
          case "www.moneycontrol.com":
          case "moneycontrol.com":
            published_date = $('meta[name="Last-Modified"]').attr("content");
            //published_date = $('div.article_schedule').text().split("/").map(el => el.trim()).join(" ");
            updated_date = published_date;
            break;
          case "www.filmibeat.com":
          case "filmibeat.com":
            published_date = $("div.date-time > span > time").attr("datetime");
            updated_date = published_date;
            break;

          case "www.newindianexpress.com":
          case "newindianexpress.com":
            published_date = $("p.ArticlePublish > span").first().text();
            updated_date = $("p.ArticlePublish > span").last().text();
            break;
          case "infotech.indiatimes.com":
          case "www.gadgetsnow.com":
          case "gadgetsnow.com":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            // published_date = $('div._2NQ8B').contents().filter(function () {
            //     return this.type === 'text';
            // }).last().text().split("Updated: ").pop();
            // updated_date = published_date;
            break;
          case "www.thenewsminute.com":
          case "thenewsminute.com":
            // Neutral Timezone
            // published_date = new Date(parseInt($('span.time.createddate').attr("data-create")) * 1000);
            // updated_date = published_date;
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.drivespark.com":
          case "drivespark.com":
            //Modify Date is mention as Array
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            updated_date =
              updated_date == "Array" ? published_date : updated_date;
            //updated_date = $('div.time-date > span > time').attr("datetime");
            break;
          case "www.carandbike.com":
          case "carandbike.com":
            published_date = toTimestamp(
              $("span.dateText").text().split("ago")[0]
            );
            updated_date = published_date;
            break;
          case "www.mykhel.com":
          case "mykhel.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            // published_date = $('div.os-posted-by > span > time').attr("datetime");
            // updated_date = published_date;
            break;
          case "markets.businessinsider.com":
          case "www.businessinsider.com":
          case "businessinsider.com":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            if (!published_date) {
              published_date = $("div.byline-timestamp").attr("data-timestamp");
              updated_date = published_date;
            }
            break;
          case "www.buzzfeed.com":
          case "buzzfeed.com":
            published_date = $(
              "span.headline-timestamp_timestamp__i0hoN > time"
            ).attr("datetime");
            updated_date = published_date;
            break;
          case "www.theguardian.com":
          case "theguardian.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            // published_date = $('details.dcr-km9fgb > summary.dcr-h56grb').text();
            // updated_date = $('details.dcr-km9fgb').contents().filter(function () {
            //     return this.type === 'text';
            // }).last().text().split("Last modified on ").pop();
            break;
          case "www.indiatoday.in":
          case "indiatoday.in":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            if (!published_date) {
              published_date = $(
                'meta[property="article:published_time"]'
              ).attr("content");
              updated_date = $('meta[property="article:modified_time"]').attr(
                "content"
              );
            }
            break;
          case "www.news18.com":
          case "news18.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            if (!published_date) {
              published_date = $("div.article_headline > p > span")
                .contents()
                .filter(function () {
                  return this.type === "text";
                })
                .last()
                .text();
              updated_date = published_date;
            }
            break;
          case "www.ndtv.com":
          case "ndtv.com":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");

            if (!updated_date) {
              updated_date = published_date;
            }
            //published_date = $('span.pst-by_lnk > meta[itemprop="datePublished"]').attr("content");
            //updated_date = $('span.pst-by_lnk > span[itemprop="dateModified"]').attr("content");
            break;
          case "www.goodreturns.in":
          case "goodreturns.in":
            //     published_date = $('meta[itemprop="datePublished"]').attr("content");
            //     updated_date = $('div.date_time > span > time').attr("datetime");
            published_date =
              $('meta[itemprop="datePublished"]').attr("content") ||
              $('meta[property="article:published_time"]').attr("content");
            updated_date =
              $('meta[itemprop="dateModified"]').attr("content") ||
              $('meta[property="article:modified_time"]').attr("content");
            if (!updated_date) {
              updated_date = published_date;
            }
            break;
          case "www.indiatv.in":
          case "indiatv.in":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.thehindu.com":
          case "thehindu.com":
            published_date = $('meta[name="publish-date"]').attr("content");
            updated_date = $('meta[name="modified-date"]').attr("content");
            if (!published_date) {
              published_date = $(
                'meta[property="article:published_time"]'
              ).attr("content");
              updated_date = $('meta[property="article:modified_time"]').attr(
                "content"
              );
            }
            break;
          case "www.oneindia.com":
          case "oneindia.com":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            if (!published_date) {
              published_date = $(
                'meta[property="article:published_time"]'
              ).attr("content");
            }
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            if (!updated_date) {
              updated_date = $('meta[property="article:modified_time"]').attr(
                "content"
              );
            }
            if (!updated_date) {
              updated_date = published_date;
            }
            break;
          case "www.firstpost.in":
          case "firstpost.in":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.firstpost.in":
          case "firstpost.in":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.abplive.in":
          case "abplive.in":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.jagranjosh.com":
          case "jagranjosh.com":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            if (!published_date) {
              published_date = $(
                'meta[property="article:published_time"]'
              ).attr("content");
              updated_date = $('meta[property="article:modified_time"]').attr(
                "content"
              );
            }
            break;
          case "www.bhaskarhindi.com":
          case "bhaskarhindi.com":
            published_date = $("div.time")
              .contents()
              .filter(function () {
                return this.type === "text";
              })
              .last()
              .text()
              .trim();
            updated_date = published_date;
            break;
          case "www.news24.com":
          case "news24.com":
            published_date = $('meta[name="publisheddate"]').attr("content");
            updated_date = $('meta[name="datemodified"]').attr("content");
            break;

          case "www.businesstoday.in":
          case "businesstoday.in":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );

            break;
          case "www.reutersagency.com":
          case "reutersagency.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.deccanchronicle.com":
          case "deccanchronicle.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.scroll.in":
          case "scroll.in":
            published_date = $('meta[name="dcterms.available"]').attr(
              "content"
            );
            updated_date = $('meta[name="dcterms.created"]').attr("content");
            break;

          case "www.freepressjournal.in":
          case "freepressjournal.in":
            published_date = $("div.updated-time")
              .contents()
              .filter(function () {
                return this.type === "text";
              })
              .last()
              .text()
              .trim();
            updated_date = published_date;
            break;

          case "www.telanganatoday.com":
          case "telanganatoday.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.dkoding.in":
          case "dkoding.in":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;

          case "www.informalnewz.com":
          case "informalnewz.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.apnlive.com":
          case "apnlive.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;

          case "www.livemint.com":
          case "livemint.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.zeebiz.com":
          case "zeebiz.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.aajtak.in":
          case "aajtak.in":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.bqprime.com":
          case "bqprime.com":
            // Date Adjustment; Not in Proper Timezone
            published_date = $(
              "div.published-info-module__published-info__3611I > time.published-info-module__published-on___M8Y9"
            )
              .attr("datetime")
              .split("+05:30")
              .join("+00:00");
            updated_date = $(
              "div.published-info-module__published-info__3611I > time.published-info-module__updated-on__2JWey"
            )
              .attr("datetime")
              .split("+05:30")
              .join("+00:00");
            break;

          case "www.thequint.com":
          case "thequint.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;

          case "www.thehindubusinessline.com":
          case "thehindubusinessline.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;

          case "www.bhaskar.com":
          case "bhaskar.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.jagran.com":
          case "english.jagran.com":
          case "jagran.com":
            published_date = $('meta[property="article:published_date"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_date"]').attr(
              "content"
            );
            if (!published_date) {
              published_date = $('meta[itemprop="datePublished"]').attr(
                "content"
              );
              updated_date = $('meta[itemprop="dateModified"]').attr("content");
            }
            break;
          case "www.firstpost.com":
          case "firstpost.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.abplive.com":
          case "abplive.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.hindustantimes.com":
          case "hindustantimes.com":
            published_date = $('meta[property="article:published_time"]').attr(
              "content"
            );
            updated_date = $('meta[property="article:modified_time"]').attr(
              "content"
            );
            break;
          case "www.republicworld.com":
          case "republicworld.com":
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            break;
          case "www.consumeraffairs.com":
            const datePublishedElement = $('[itemprop="datePublished"]');
            published_date = datePublishedElement.attr("datetime");
            break;
          case "pune.media":
            // const timeElement = $("time.post-published.updated");
            const publishingDateElement = $("#post-published.updated");
            console.log(publishingDateElement);
            // Extract the 'datetime' attribute
            published_date = publishingDateElement.attr("datetime");
            break;
          case "www.uniindia.com":
            let date_string = $(".storydate").text();
            console.log(date_string);
            obj.publishingDate = convertStoryDateToDate(date_string);
            break;
          default:
            published_date = $('meta[itemprop="datePublished"]').attr(
              "content"
            );
            updated_date = $('meta[itemprop="dateModified"]').attr("content");
            if (!published_date) {
              published_date = $(
                'meta[property="article:published_time"]'
              ).attr("content");
              updated_date = $('meta[property="article:modified_time"]').attr(
                "content"
              );
            }
            if (!published_date) {
              console.log("INNN");
              $("*").each(function () {
                const attributes = this.attribs;
                // Iterate over each attribute of the element
                for (const attr in attributes) {
                  if (attr.includes("datePublished")) {
                    published_date = attributes[attr];
                    console.log(published_date);
                    break;
                  }
                }
              });
            }
        }
      }
    } catch (err) {
      console.log(err);
      published_date = null;
    }

    obj.publishingDate = published_date;

    columns.push(obj);

    if (obj.text == "" || !obj.text) {
      const error = new Error("GET request not giving results");
      console.log("Results empty");
    } else {
      return callback(null, columns);
    }
  } catch (err) {
    console.log("GET request failed:", err.message);
    // Handle other errors as needed

    // Retry the request with a proxy if any error occurs
    if (retryCount < 3) {
      console.log("Retrying with proxy...");
      const proxyOptions = {
        http: "http://package-10001:uHUtgPyRMmABDjT0@rotating.proxyempire.io:5000",
        https:
          "http://package-10001:uHUtgPyRMmABDjT0@rotating.proxyempire.io:5000",
      };
      return await extract(source, callback, proxyOptions, retryCount + 1);
    }
  }
}

function convertStoryDateToDate(dateStr) {
  // const date = new Date(year, monthNumeric, day, hours, minutes);
  const monthMapping = {
    Jan: "01",
    Feb: "02",
    Mar: "03",
    Apr: "04",
    May: "05",
    Jun: "06",
    Jul: "07",
    Aug: "08",
    Sep: "09",
    Oct: "10",
    Nov: "11",
    Dec: "12",
  };

  // Extract details from the given string
  const matchResult = dateStr.match(
    /Posted at: (\w{3}) (\d{1,2}) (\d{4}) +?(\d{1,2}):(\d{2})([APM]{2})/
  );

  if (!matchResult) {
    console.error("Date format not recognized");
    return null;
  }

  const [, month, day, year, hour, minute, period] = matchResult;

  // Convert 12-hour format to 24-hour format
  let convertedHour = parseInt(hour);
  if (period === "PM" && hour !== "12") {
    convertedHour += 12;
  } else if (period === "AM" && hour === "12") {
    convertedHour = 0;
  }

  // Construct the final formatted date
  //const formattedDate = new Date(year,monthMapping[month]-1,day,convertedHour,minute);
  const formattedDate = `${year}-${monthMapping[month]}-${String(day).padStart(
    2,
    "0"
  )}T${String(convertedHour).padStart(2, "0")}:${minute}:00+05:30`;

  return formattedDate;
}

function toTimestamp(diff) {
  var currentDateObj = new Date();
  var numberOfMlSeconds = currentDateObj.getTime();
  let time_data = diff.trim().split(" ");
  time_data[0] = parseInt(time_data[0]);
  var subMlSeconds = 1000;

  switch (time_data[1]) {
    case "second":
    case "seconds":
      subMlSeconds = subMlSeconds * time_data[0];
      break;
    case "minute":
    case "minutes":
      subMlSeconds = subMlSeconds * 60 * time_data[0];
      break;
    case "hour":
    case "hours":
      subMlSeconds = subMlSeconds * 60 * 60 * time_data[0];
      break;
    case "day":
    case "days":
      subMlSeconds = subMlSeconds * 60 * 60 * 24 * time_data[0];
      break;
    case "week":
    case "weeks":
      subMlSeconds = subMlSeconds * 60 * 60 * 24 * 7 * time_data[0];
      break;
    case "month":
    case "months":
      subMlSeconds = subMlSeconds * 60 * 60 * 24 * 30.5 * time_data[0];
      break;
    case "year":
    case "years":
      subMlSeconds = subMlSeconds * 60 * 60 * 24 * 365 * time_data[0];
      break;
    case "decade":
    case "decades":
      subMlSeconds = subMlSeconds * 60 * 60 * 24 * 365 * 10 * time_data[0];
      break;
    default:
      return new Date(diff);
  }
  var newDateObj = new Date(numberOfMlSeconds - subMlSeconds);

  return newDateObj;
}

function detectNetworkBlocker(source) {
  if (
    source.search(
      /This process is automatic. Your browser will redirect to your requested content shortly./gis
    ) > -1
  ) {
    return true;
  }
  return false;
}

module.exports = { extract: extract };
